version: '3'

services:

  zookeeper:
    image: zookeeper:3.6
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog

  kafka:
    image: bitnami/kafka:2.5.0
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CLIENT_USER=admin
    volumes:
      - kafka-data:/bitnami/kafka
    depends_on:
      - "zookeeper"

  server:
    build: ../
    env_file:
      - .env
    ports:
      - 3000:3000

volumes:
  kafka-data:
  zookeeper-data:
  zookeeper-datalog: